# ========== tinytroupe/agent/learnable_utils.py ==========
"""
LearnableTinyPerson related utility functions.

This module provides helper functions for working with LearnableTinyPerson,
such as converting existing TinyPerson instances to LearnableTinyPerson.
"""

from tinytroupe.agent import TinyPerson
from tinytroupe.agent.learnable_tiny_person import LearnableTinyPerson
from tinytroupe.agent.human_corrector import HumanCorrector


def convert_to_learnable(person: TinyPerson) -> LearnableTinyPerson:
    """
    Convert a TinyPerson instance to a LearnableTinyPerson instance.
    
    This function takes an existing TinyPerson (e.g., one generated by
    TinyPersonFactory) and converts it to a LearnableTinyPerson by:
      1. Creating a new LearnableTinyPerson instance
      2. Copying all attributes from the original TinyPerson
      3. Initializing LearnableTinyPerson-specific attributes
      4. Updating the agent registry
    
    Args:
        person (TinyPerson): The TinyPerson instance to convert
    
    Returns:
        LearnableTinyPerson: The converted LearnableTinyPerson instance
    
    Example:
        >>> from tinytroupe.factory import TinyPersonFactory
        >>> from tinytroupe.agent.learnable_utils import convert_to_learnable
        >>> 
        >>> factory = TinyPersonFactory("Academic Context")
        >>> regular_agent = factory.generate_person("Researcher")
        >>> 
        >>> # Convert to learnable agent
        >>> learnable_agent = convert_to_learnable(regular_agent)
        >>> learnable_agent.set_training_mode(True)
    """
    # 1. Create a new LearnableTinyPerson instance (without calling __init__)
    learnable = LearnableTinyPerson.__new__(LearnableTinyPerson)
    
    # 2. Copy all attributes from the original TinyPerson
    learnable.__dict__.update(person.__dict__)
    
    # 3. Initialize LearnableTinyPerson-specific attributes
    learnable.human_corrector = HumanCorrector(learnable)
    learnable.training_mode = False
    
    # ========== 修正: __init__と同じ完全な統計辞書を作成 ==========
    learnable.intervention_statistics = {
        "total_interventions": 0,
        "interventions_by_type": {},
        "actions_generated": 0,
        "actions_accepted_without_intervention": 0,
        "quality_check_failures": 0,  # ← 追加
        "quality_check_passes": 0     # ← 追加
    }
    # ========== ここまで修正 ==========
    
    # 4. Update the agent registry
    if person.name in TinyPerson.all_agents:
        del TinyPerson.all_agents[person.name]
        print(f"✅ Removed {person.name} from TinyPerson.all_agents")
    
    # 新しいLearnableTinyPersonを登録
    TinyPerson.add_agent(learnable)
    print(f"✅ Added {learnable.name} as LearnableTinyPerson to all_agents")
    
    return learnable